name: Docker Image CI/CD

on:
  release:
    types: [created]
  pull_request:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Cambia esto a la versión que necesites

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --silent

      - name: Extract version
        id: extract_version
        if: github.event_name == 'release'
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/opcua-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/opcua-gateway:${{ steps.extract_version.outputs.VERSION }}

      - name: Build only (for PR)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
